name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # once a day
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0.10
        with:
          owner: base-org
          repo: node
          head: main
          base: main
          pr_title: Sync fork repo
          pr_message: Merge latest changes from upstream repo
